// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package cart

import (
	"context"
)

type Querier interface {
	AddCartItem(ctx context.Context, arg AddCartItemParams) error
	ClearCart(ctx context.Context, userID int64) error
	DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) error
	GetCartItems(ctx context.Context, userID int64) ([]GetCartItemsRow, error)
}

var _ Querier = (*Queries)(nil)
