// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package cart

import (
	"context"
)

const addCartItem = `-- name: AddCartItem :exec
INSERT INTO cart_items (user_id, sku, count)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, sku)
DO UPDATE SET count = cart_items.count + EXCLUDED.count
`

type AddCartItemParams struct {
	UserID int64 `json:"user_id"`
	Sku    int64 `json:"sku"`
	Count  int64 `json:"count"`
}

func (q *Queries) AddCartItem(ctx context.Context, arg AddCartItemParams) error {
	_, err := q.db.Exec(ctx, addCartItem, arg.UserID, arg.Sku, arg.Count)
	return err
}

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart_items
WHERE user_id = $1
`

func (q *Queries) ClearCart(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, clearCart, userID)
	return err
}

const deleteCartItem = `-- name: DeleteCartItem :exec
DELETE FROM cart_items
WHERE user_id = $1 AND sku = $2
`

type DeleteCartItemParams struct {
	UserID int64 `json:"user_id"`
	Sku    int64 `json:"sku"`
}

func (q *Queries) DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) error {
	_, err := q.db.Exec(ctx, deleteCartItem, arg.UserID, arg.Sku)
	return err
}

const getCartItems = `-- name: GetCartItems :many
SELECT sku, count 
FROM cart_items
WHERE user_id = $1
`

type GetCartItemsRow struct {
	Sku   int64 `json:"sku"`
	Count int64 `json:"count"`
}

func (q *Queries) GetCartItems(ctx context.Context, userID int64) ([]GetCartItemsRow, error) {
	rows, err := q.db.Query(ctx, getCartItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCartItemsRow
	for rows.Next() {
		var i GetCartItemsRow
		if err := rows.Scan(&i.Sku, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
