// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package product

type LomsProduct struct {
	Sku   int64  `json:"sku"`
	Name  string `json:"name"`
	Price int64  `json:"price"`
}
