// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package product

import (
	"context"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (int64, error)
	GetProduct(ctx context.Context, sku int64) (LomsProduct, error)
}

var _ Querier = (*Queries)(nil)
