// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package product

import (
	"context"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO loms.products (name, price)
VALUES ($1, $2)
RETURNING sku
`

type CreateProductParams struct {
	Name  string `json:"name"`
	Price int64  `json:"price"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (int64, error) {
	row := q.db.QueryRow(ctx, createProduct, arg.Name, arg.Price)
	var sku int64
	err := row.Scan(&sku)
	return sku, err
}

const getProduct = `-- name: GetProduct :one
SELECT sku, name, price
FROM loms.products
WHERE sku = $1
`

func (q *Queries) GetProduct(ctx context.Context, sku int64) (LomsProduct, error) {
	row := q.db.QueryRow(ctx, getProduct, sku)
	var i LomsProduct
	err := row.Scan(&i.Sku, &i.Name, &i.Price)
	return i, err
}
