// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package outbox

import (
	"context"
)

type Querier interface {
	GetOutboxMessages(ctx context.Context, arg GetOutboxMessagesParams) ([]GetOutboxMessagesRow, error)
	MarkOutboxMessagesAsProcessed(ctx context.Context, idempotencyKeys []string) (int64, error)
	MarkOutboxMessagesAsRetryable(ctx context.Context, idempotencyKeys []string) (int64, error)
	SendOutboxMessage(ctx context.Context, arg SendOutboxMessageParams) error
}

var _ Querier = (*Queries)(nil)
