// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package order

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type LomsOrderStatus string

const (
	LomsOrderStatusNew             LomsOrderStatus = "new"
	LomsOrderStatusAwaitingpayment LomsOrderStatus = "awaiting payment"
	LomsOrderStatusFailed          LomsOrderStatus = "failed"
	LomsOrderStatusPaid            LomsOrderStatus = "paid"
	LomsOrderStatusCancelled       LomsOrderStatus = "cancelled"
)

func (e *LomsOrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LomsOrderStatus(s)
	case string:
		*e = LomsOrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LomsOrderStatus: %T", src)
	}
	return nil
}

type NullLomsOrderStatus struct {
	LomsOrderStatus LomsOrderStatus `json:"loms_order_status"`
	Valid           bool            `json:"valid"` // Valid is true if LomsOrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLomsOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LomsOrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LomsOrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLomsOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LomsOrderStatus), nil
}

type LomsOrder struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Status    LomsOrderStatus    `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
