// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package order

import (
	"context"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO loms.orders (user_id, status)
VALUES (
            $1,
            'awaiting payment'::loms.order_status
        )
RETURNING id
`

func (q *Queries) CreateOrder(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, createOrder, userID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO loms.order_info (order_id, sku, count)
VALUES ($1, $2, $3)
`

type CreateOrderItemParams struct {
	OrderID int64 `json:"order_id"`
	Sku     int64 `json:"sku"`
	Count   int64 `json:"count"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.Exec(ctx, createOrderItem, arg.OrderID, arg.Sku, arg.Count)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT o.id, o.user_id, o.status, o.created_at, o.updated_at
FROM loms.orders o
WHERE o.id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id int64) (LomsOrder, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i LomsOrder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderForUpdateByID = `-- name: GetOrderForUpdateByID :one
SELECT id, user_id, status, created_at, updated_at
FROM loms.orders
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetOrderForUpdateByID(ctx context.Context, id int64) (LomsOrder, error) {
	row := q.db.QueryRow(ctx, getOrderForUpdateByID, id)
	var i LomsOrder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderItems = `-- name: GetOrderItems :many
SELECT sku, count
FROM loms.order_info
WHERE order_id = $1
`

type GetOrderItemsRow struct {
	Sku   int64 `json:"sku"`
	Count int64 `json:"count"`
}

func (q *Queries) GetOrderItems(ctx context.Context, orderID int64) ([]GetOrderItemsRow, error) {
	rows, err := q.db.Query(ctx, getOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderItemsRow
	for rows.Next() {
		var i GetOrderItemsRow
		if err := rows.Scan(&i.Sku, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :execrows
UPDATE loms.orders
SET status = $2
WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID     int64           `json:"id"`
	Status LomsOrderStatus `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOrderStatus, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
