// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package order

import (
	"context"
)

type Querier interface {
	CreateOrder(ctx context.Context, userID int64) (int64, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error
	GetOrder(ctx context.Context, id int64) (LomsOrder, error)
	GetOrderForUpdateByID(ctx context.Context, id int64) (LomsOrder, error)
	GetOrderItems(ctx context.Context, orderID int64) ([]GetOrderItemsRow, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
