// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package stocks

import (
	"context"
)

const addToAvailableStock = `-- name: AddToAvailableStock :exec
INSERT INTO loms.available_stocks AS a (sku, count)
VALUES ($1, $2)
ON CONFLICT (sku) DO UPDATE
    SET count = a.count + EXCLUDED.count
`

type AddToAvailableStockParams struct {
	Sku   int64 `json:"sku"`
	Count int64 `json:"count"`
}

func (q *Queries) AddToAvailableStock(ctx context.Context, arg AddToAvailableStockParams) error {
	_, err := q.db.Exec(ctx, addToAvailableStock, arg.Sku, arg.Count)
	return err
}

const createStock = `-- name: CreateStock :exec
INSERT INTO loms.available_stocks (sku, count)
VALUES ($1, 0)
`

func (q *Queries) CreateStock(ctx context.Context, sku int64) error {
	_, err := q.db.Exec(ctx, createStock, sku)
	return err
}

const decrementAvailableStock = `-- name: DecrementAvailableStock :execrows
UPDATE loms.available_stocks
SET count = count - $2
WHERE sku = $1
  AND count >= $2
`

type DecrementAvailableStockParams struct {
	Sku   int64 `json:"sku"`
	Count int64 `json:"count"`
}

func (q *Queries) DecrementAvailableStock(ctx context.Context, arg DecrementAvailableStockParams) (int64, error) {
	result, err := q.db.Exec(ctx, decrementAvailableStock, arg.Sku, arg.Count)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAvailableStockAmount = `-- name: GetAvailableStockAmount :one
SELECT COALESCE(
               (SELECT count
                FROM loms.available_stocks
                WHERE sku = $1),
               0
       )::integer AS count
`

func (q *Queries) GetAvailableStockAmount(ctx context.Context, sku int64) (int32, error) {
	row := q.db.QueryRow(ctx, getAvailableStockAmount, sku)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const upsertAvailableStock = `-- name: UpsertAvailableStock :exec
INSERT INTO loms.available_stocks (sku, count)
VALUES ($1, $2)
ON CONFLICT (sku) DO UPDATE SET count = EXCLUDED.count
`

type UpsertAvailableStockParams struct {
	Sku   int64 `json:"sku"`
	Count int64 `json:"count"`
}

func (q *Queries) UpsertAvailableStock(ctx context.Context, arg UpsertAvailableStockParams) error {
	_, err := q.db.Exec(ctx, upsertAvailableStock, arg.Sku, arg.Count)
	return err
}
